### ISSUE TITLE
libiconv has the different function definitions

### ISSUE THREAD

**Issue by sunxfancy** [lasote/conan-libiconv#3]
There are some differents in the definition of the function iconv.

```c
size_t iconv(libiconv_t, char**, size_t*, char**, size_t*);  // linux version
size_t iconv(libiconv_t, const char**, size_t*, char**, size_t*); // winiconv
```

This code seems being changed: https://github.com/lasote/iconv-for-windows/blob/master/include/iconv.h#L102
Please check the version.

**Comment by sunxfancy** [comment]
How about having a look at this project: https://github.com/win-iconv/win-iconv
They use a macro to deal with this problem:
https://github.com/win-iconv/win-iconv/blob/master/iconv.h

**Comment by lasote** [comment]
HI! Sorry for the big big delay,

I've added a new option to the winiconv conan package to change the function prototype with or without the "const".
The default is the "const" but if you want to use the prototype without const you have to require the package with this option:

`` -o winiconv:non_const_iconv=True``

You can add that option to your `conan install` command or declare it in your `conanfile.txt`:

```
[requires]
libiconv/1.14@lasote/stable

[options]
winiconv:non_const_iconv=True
```

PD: It's not needed to write the winiconv requirement, it will be propagated to the recursive require.
